version: "3.9"
services:
  frontend:
    image: node:20-alpine
    working_dir: /app
    # build: ./frontend
    command: npm run dev
    volumes:
      - ./next-frontend:/app
    ports:
      - "3000:3000"
    environment:
    - NODE_ENV=development
    - NEXT_PUBLIC_API_URL=http://api:8000
    depends_on:
      - api
    networks: [vidnet]

  api:
    build:
          context: ./python-api
          dockerfile: Dockerfile
    env_file: .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - ./python-api:/usr/src/app
      - ./media:/usr/src/app/media
    depends_on:
      - redis
      - db
    networks: [vidnet]

  worker:
    build:
      context: ./go-worker
      dockerfile: Dockerfile.dev
    env_file: .env
    volumes:
    - ./go-worker:/app
    - ./media:/app/media
    command: go run cmd/api/main.go
    depends_on:
      - redis
      - db
    networks: [vidnet]

  redis:
    image: redis:7
    networks: [vidnet]
    volumes:
      - redisdata:/data
    ports:
      - 6379:6379

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vidflow
    volumes:
      - db_data:/var/lib/postgresql/data
    networks: [vidnet]

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks: [vidnet]
    volumes:
      - pgadmin_data:/var/lib/pgadmin
  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks: [vidnet]
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/config/nginx/conf.d.local/:/etc/nginx/conf.d/
      - ./docker/config/nginx/conf.d.local/ssl:/etc/nginx/ssl/
      - ./media:/var/www/media
    depends_on:
      - frontend
    networks: [vidnet]

volumes:
  db_data:
  redisdata:
    driver: local
  pgadmin_data:
    driver: local

networks:
  vidnet:
    driver: bridge